START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209084702_1.0.0.1') THEN
    CREATE TABLE "CountryInfos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50),
        "CNName" character varying(50),
        "CCA2" character varying(10),
        "CCA3" character varying(10),
        "CCN3" character varying(10),
        "Currency" character varying(100),
        "AreaPhoneCode" character varying(150),
        "Region" character varying(50),
        "SubRegion" character varying(50),
        "CnRegion" character varying(50),
        "CnSubRegion" character varying(50),
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_CountryInfos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209084702_1.0.0.1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251209084702_1.0.0.1', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100235_1.0.0.2') THEN
    ALTER TABLE "ClientUsers" ADD "AbpUserId" bigint NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210100235_1.0.0.2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251210100235_1.0.0.2', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211085539_1.0.0.3') THEN
    ALTER TABLE "AbpUsers" ADD "UserType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211085539_1.0.0.3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251211085539_1.0.0.3', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212041853_1.0.0.4') THEN
    ALTER TABLE "VAAccountIdentities" ALTER COLUMN "AccountId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212041853_1.0.0.4') THEN
    ALTER TABLE "VAAccountIdentities" ADD "Extra" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212041853_1.0.0.4') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251212041853_1.0.0.4', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "Address";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "City";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "DocumentNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "DocumentPhotoBackUrl";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "DocumentPhotoFrontUrl";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "FirstName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "LastName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "MiddleName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "PostalCode";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" DROP COLUMN "RejectReason";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" RENAME COLUMN "Extra" TO "FormJson";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" RENAME COLUMN "DocumentType" TO "AccountUserType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    ALTER TABLE "VAAccountIdentities" ALTER COLUMN "Status" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    UPDATE "VAAccountIdentities" SET "MerchantId" = 0 WHERE "MerchantId" IS NULL;
    ALTER TABLE "VAAccountIdentities" ALTER COLUMN "MerchantId" SET NOT NULL;
    ALTER TABLE "VAAccountIdentities" ALTER COLUMN "MerchantId" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215035100_1.0.0.5') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251215035100_1.0.0.5', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    CREATE TABLE "AppKycApplicants" (
        "Id" uuid NOT NULL,
        "UserId" bigint NOT NULL,
        "KycProvider" text,
        "KycChannelProductTypes" integer NOT NULL,
        "KycType" integer NOT NULL,
        "KycLevelName" integer NOT NULL,
        "KycVerificationLink" text,
        "KycBizStatus" integer NOT NULL,
        "KycChannelStatus" text,
        "ApplicantId" text,
        "InspectionId" text,
        "ExternalUserId" text,
        "ClientId" text,
        "ApiKey" text,
        "ApplicantType" text,
        "ApplicantPlatform" text,
        "IpCountry" text,
        "FirstName" text,
        "FirstNameEn" text,
        "LastName" text,
        "LastNameEn" text,
        "DateOfBirth" timestamp with time zone,
        "Country" text,
        "FixedFirstName" text,
        "FixedFirstNameEn" text,
        "FixedLastName" text,
        "FixedLastNameEn" text,
        "FixedDob" timestamp with time zone,
        "Gender" text,
        "Nationality" text,
        "TaxResidenceCountry" text,
        "Street" text,
        "State" text,
        "BuildingNumber" text,
        "Town" text,
        "PostCode" text,
        "FormattedAddress" text,
        "CompanyName" text,
        "CompanyRegistrationNumber" text,
        "CompanyCountry" text,
        "CompanyLegalAddress" text,
        "CompanyEmail" text,
        "OwnershipStructureDepth" integer,
        "SkippedBeneficiaryTypes" text,
        "Email" text,
        "ReviewStatus" text,
        "ReviewAnswer" text,
        "ReviewRejectType" text,
        "ModerationComment" text,
        "ReviewLevel" text,
        "ReviewAttemptCount" integer,
        "Priority" integer,
        "ReviewDate" timestamp with time zone,
        "ClientComment" text,
        "RejectLabels" text,
        "AgreementAcceptedAt" timestamp with time zone,
        "AgreementSource" text,
        "EmploymentStatus" text,
        "AnnualIncome" text,
        "IdDocType" text,
        "IdDocCountry" text,
        "IdDocNumber" text,
        "IdDocValidUntil" timestamp with time zone,
        "HasSelfie" boolean,
        "HasVideo" boolean,
        "HasProofOfAddress" boolean,
        "FileInfos" text,
        "QuestionnaireJson" text,
        "RequiredIdDocsJson" text,
        "RawJson" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedTime" timestamp with time zone,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_AppKycApplicants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AppKycApplicants_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    CREATE TABLE "AppKycApplicantBeneficiaries" (
        "Id" uuid NOT NULL,
        "KycApplicantId" uuid NOT NULL,
        "BeneficiaryApplicantId" text,
        "BeneficiaryId" text,
        "Role" text,
        "Submitted" boolean NOT NULL,
        "FirstName" text,
        "LastName" text,
        "MiddleName" text,
        "DateOfBirth" timestamp with time zone,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_AppKycApplicantBeneficiaries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AppKycApplicantBeneficiaries_AppKycApplicants_KycApplicantId" FOREIGN KEY ("KycApplicantId") REFERENCES "AppKycApplicants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    CREATE TABLE "AppKycApplicantDocuments" (
        "Id" uuid NOT NULL,
        "KycApplicantId" uuid NOT NULL,
        "InspectionId" text,
        "IdDocType" text,
        "ImageId" text,
        "ImageSlot" integer NOT NULL,
        "Country" text,
        "ReviewAnswer" text,
        "ModerationComment" text,
        "ClientComment" text,
        "Url" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_AppKycApplicantDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AppKycApplicantDocuments_AppKycApplicants_KycApplicantId" FOREIGN KEY ("KycApplicantId") REFERENCES "AppKycApplicants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    CREATE INDEX "IX_AppKycApplicantBeneficiaries_KycApplicantId" ON "AppKycApplicantBeneficiaries" ("KycApplicantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    CREATE INDEX "IX_AppKycApplicantDocuments_KycApplicantId" ON "AppKycApplicantDocuments" ("KycApplicantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    CREATE INDEX "IX_AppKycApplicants_UserId" ON "AppKycApplicants" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260109074515_carl_1.0.0.6') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260109074515_carl_1.0.0.6', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112034806_carl_1.0.0.7') THEN
    ALTER TABLE "AbpUsers" ADD "KycLevelCompleted" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112034806_carl_1.0.0.7') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260112034806_carl_1.0.0.7', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112100912_1.0.0.8') THEN
    CREATE TABLE "MerchantChannelCurrencies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MerchantId" integer NOT NULL,
        "ChannelCode" text,
        "Currency" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_MerchantChannelCurrencies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112100912_1.0.0.8') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260112100912_1.0.0.8', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    ALTER TABLE "MerchantChannelCurrencies" ADD "OpenClose" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    CREATE TABLE "PayChannelCustomers" (
        "Id" uuid NOT NULL,
        "UserId" bigint NOT NULL,
        "ChannelProvider" character varying(32) NOT NULL,
        "ChannelCustomerId" character varying(64),
        "Status" character varying(32),
        "EntityType" character varying(32),
        "RawData" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_PayChannelCustomers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayChannelCustomers_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    CREATE TABLE "PayChannelAccounts" (
        "Id" uuid NOT NULL,
        "UserId" bigint NOT NULL,
        "CustomerId" uuid NOT NULL,
        "ChannelProvider" character varying(32) NOT NULL,
        "ChannelAccountId" character varying(64),
        "Currency" character varying(10) NOT NULL,
        "AccountName" character varying(128),
        "AccountNumber" character varying(128),
        "BankName" character varying(128),
        "Status" character varying(32),
        "RejectionReason" text,
        "RawData" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_PayChannelAccounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayChannelAccounts_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PayChannelAccounts_PayChannelCustomers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "PayChannelCustomers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    CREATE INDEX "IX_PayChannelAccounts_CustomerId" ON "PayChannelAccounts" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    CREATE INDEX "IX_PayChannelAccounts_UserId" ON "PayChannelAccounts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    CREATE INDEX "IX_PayChannelCustomers_UserId" ON "PayChannelCustomers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113041639_1.0.0.9') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113041639_1.0.0.9', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080256_RenameOpenCloseToStatus') THEN
    ALTER TABLE "MerchantChannelCurrencies" RENAME COLUMN "OpenClose" TO "Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080256_RenameOpenCloseToStatus') THEN
    ALTER TABLE "MerchantChannelCurrencies" ADD "BalanceTime" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080256_RenameOpenCloseToStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113080256_RenameOpenCloseToStatus', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080557_RemoveBalanceTime') THEN
    ALTER TABLE "MerchantChannelCurrencies" DROP COLUMN "BalanceTime";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080557_RemoveBalanceTime') THEN
    ALTER TABLE "MerchantChannelCurrencies" DROP COLUMN "ChannelCode";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080557_RemoveBalanceTime') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113080557_RemoveBalanceTime', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080951_RevertFieldNames') THEN
    ALTER TABLE "MerchantChannelCurrencies" RENAME COLUMN "Status" TO "OpenClose";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080951_RevertFieldNames') THEN
    ALTER TABLE "MerchantChannelCurrencies" ADD "BalanceTime" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080951_RevertFieldNames') THEN
    ALTER TABLE "MerchantChannelCurrencies" ADD "ChannelCode" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113080951_RevertFieldNames') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113080951_RevertFieldNames', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113081043_RemoveBalanceTimeOnly') THEN
    ALTER TABLE "MerchantChannelCurrencies" DROP COLUMN "BalanceTime";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113081043_RemoveBalanceTimeOnly') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113081043_RemoveBalanceTimeOnly', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113091033_1.0.0.10') THEN
    CREATE TABLE "DataDictionaries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DicKey" text,
        "DicValue" text,
        "Description" text,
        "DicType" integer NOT NULL,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_DataDictionaries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113091033_1.0.0.10') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113091033_1.0.0.10', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115021903_Added_PayChannelRequestLog') THEN
    CREATE TABLE "PayChannelRequestLogs" (
        "Id" uuid NOT NULL,
        "TenantId" integer,
        "UserId" bigint NOT NULL,
        "ChannelProvider" character varying(32) NOT NULL,
        "RequestType" character varying(64) NOT NULL,
        "RequestPayload" text,
        "ResponsePayload" text,
        "Status" character varying(32),
        "ErrorMessage" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_PayChannelRequestLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayChannelRequestLogs_AbpUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AbpUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115021903_Added_PayChannelRequestLog') THEN
    CREATE INDEX "IX_PayChannelRequestLogs_UserId" ON "PayChannelRequestLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115021903_Added_PayChannelRequestLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260115021903_Added_PayChannelRequestLog', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN

                    ALTER TABLE "PayChannelCustomers" 
                    ALTER COLUMN "Status" TYPE integer 
                    USING CASE 
                        WHEN upper("Status") = 'ACTIVE' THEN 1 
                        WHEN upper("Status") = 'FROZEN' THEN 2 
                        WHEN upper("Status") = 'DISABLE' OR upper("Status") = 'DISABLED' THEN 3 
                        WHEN upper("Status") = 'FAILED' THEN 4 
                        ELSE 0 
                    END;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN

                    ALTER TABLE "PayChannelCustomers" 
                    ALTER COLUMN "EntityType" TYPE integer 
                    USING CASE 
                        WHEN upper("EntityType") = 'COMPANY' THEN 1 
                        ELSE 0 
                    END;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN

                    ALTER TABLE "PayChannelAccounts" 
                    ALTER COLUMN "Status" TYPE integer 
                    USING CASE 
                        WHEN upper("Status") = 'ACTIVE' THEN 1 
                        WHEN upper("Status") = 'FAILED' THEN 2 
                        WHEN upper("Status") = 'SUSPENDED' THEN 3 
                        WHEN upper("Status") = 'CLOSED' THEN 4 
                        ELSE 0 
                    END;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "Status" TYPE integer;
    UPDATE "PayChannelCustomers" SET "Status" = 0 WHERE "Status" IS NULL;
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "Status" SET NOT NULL;
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "Status" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "EntityType" TYPE integer;
    UPDATE "PayChannelCustomers" SET "EntityType" = 0 WHERE "EntityType" IS NULL;
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "EntityType" SET NOT NULL;
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "EntityType" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN
    ALTER TABLE "PayChannelAccounts" ALTER COLUMN "Status" TYPE integer;
    UPDATE "PayChannelAccounts" SET "Status" = 0 WHERE "Status" IS NULL;
    ALTER TABLE "PayChannelAccounts" ALTER COLUMN "Status" SET NOT NULL;
    ALTER TABLE "PayChannelAccounts" ALTER COLUMN "Status" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115034210_Refactor_Status_To_Enum') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260115034210_Refactor_Status_To_Enum', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115040202_Add_ReferenceId_To_PayChannelCustomer') THEN
    ALTER TABLE "PayChannelCustomers" ADD "ReferenceId" character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115040202_Add_ReferenceId_To_PayChannelCustomer') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260115040202_Add_ReferenceId_To_PayChannelCustomer', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115041356_Add_ReferenceId_To_PayChannelAccount') THEN
    ALTER TABLE "PayChannelAccounts" ADD "ReferenceId" character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115041356_Add_ReferenceId_To_PayChannelAccount') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260115041356_Add_ReferenceId_To_PayChannelAccount', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115042204_Add_PaymentMethods_Table') THEN
    CREATE TABLE "PayChannelAccountPaymentMethods" (
        "Id" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "PaymentType" character varying(32) NOT NULL,
        "AccountHolderName" character varying(128),
        "AccountNumber" character varying(128),
        "AccountRoutingNumber" character varying(128),
        "Memo" character varying(128),
        "SwiftBic" character varying(128),
        "IntermediarySwiftBic" character varying(128),
        "InstitutionName" character varying(128),
        "InstitutionAddressLine1" character varying(256),
        "InstitutionCity" character varying(128),
        "InstitutionState" character varying(128),
        "InstitutionPostalCode" character varying(128),
        "InstitutionCountryCode" character varying(10),
        "HolderAddressLine1" character varying(256),
        "HolderCity" character varying(128),
        "HolderState" character varying(128),
        "HolderPostalCode" character varying(128),
        "HolderCountryCode" character varying(10),
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_PayChannelAccountPaymentMethods" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayChannelAccountPaymentMethods_PayChannelAccounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "PayChannelAccounts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115042204_Add_PaymentMethods_Table') THEN
    CREATE INDEX "IX_PayChannelAccountPaymentMethods_AccountId" ON "PayChannelAccountPaymentMethods" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115042204_Add_PaymentMethods_Table') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260115042204_Add_PaymentMethods_Table', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115065209_Add_Payloads_To_Customer') THEN
    ALTER TABLE "PayChannelCustomers" ADD "CallbackPayload" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115065209_Add_Payloads_To_Customer') THEN
    ALTER TABLE "PayChannelCustomers" ADD "RequestPayload" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115065209_Add_Payloads_To_Customer') THEN
    ALTER TABLE "PayChannelCustomers" ADD "ResponsePayload" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260115065209_Add_Payloads_To_Customer') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260115065209_Add_Payloads_To_Customer', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119022113_1.0.0.11') THEN
    ALTER TABLE "UserIdentities" ADD "Birthday" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119022113_1.0.0.11') THEN
    ALTER TABLE "UserIdentities" ADD "CountryCode" character varying(10);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119022113_1.0.0.11') THEN
    ALTER TABLE "UserIdentities" ADD "Sex" character varying(10);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119022113_1.0.0.11') THEN
    ALTER TABLE "UserIdentities" ADD "State" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119022113_1.0.0.11') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119022113_1.0.0.11', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119065309_1.0.0.12') THEN
    CREATE TABLE "VAAccountIdentityDetails" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VAAccountIdentityId" integer NOT NULL,
        "AccountHolderName" character varying(255),
        "AccountHolderType" character varying(20),
        "AccountHolderAddressLine1" character varying(255),
        "AccountHolderAddressLine2" character varying(255),
        "AccountHolderCity" character varying(255),
        "AccountHolderState" character varying(50),
        "AccountHolderPostalCode" character varying(30),
        "AccountHolderCountryCode" character varying(2),
        "BankName" character varying(255),
        "BankBranchName" character varying(255),
        "BankAddressLine1" character varying(255),
        "BankAddressLine2" character varying(255),
        "BankCity" character varying(255),
        "BankState" character varying(50),
        "BankPostalCode" character varying(30),
        "BankCountryCode" character varying(2),
        "SwiftBic" character varying(11),
        "IntermediaryBankName" character varying(255),
        "IntermediaryBankSwift" character varying(11),
        "AchRoutingNumber" character varying(9),
        "AbaRoutingNumber" character varying(9),
        "FedwireRoutingNumber" character varying(9),
        "WireRoutingNumber" character varying(9),
        "AccountNumber" character varying(34),
        "AccountType" character varying(20),
        "WireMemo" character varying(255),
        "AchCompanyId" character varying(10),
        "AchStandardEntryClass" character varying(10),
        "Iban" character varying(34),
        "SortCode" character varying(6),
        "BsbCode" character varying(6),
        "Clabe" character varying(18),
        "BankCode" character varying(20),
        "BranchCode" character varying(20),
        "Extra" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_VAAccountIdentityDetails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VAAccountIdentityDetails_VAAccountIdentities_VAAccountIdent~" FOREIGN KEY ("VAAccountIdentityId") REFERENCES "VAAccountIdentities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119065309_1.0.0.12') THEN
    CREATE INDEX "IX_VAAccountIdentityDetails_VAAccountIdentityId" ON "VAAccountIdentityDetails" ("VAAccountIdentityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119065309_1.0.0.12') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119065309_1.0.0.12', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119074410_1.0.0.13') THEN
    ALTER TABLE "AppKycApplicants" DROP CONSTRAINT "FK_AppKycApplicants_AbpUsers_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119074410_1.0.0.13') THEN
    ALTER TABLE "AppKycApplicants" ALTER COLUMN "UserId" TYPE integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119074410_1.0.0.13') THEN
    ALTER TABLE "AppKycApplicants" ADD CONSTRAINT "FK_AppKycApplicants_ClientUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ClientUsers" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119074410_1.0.0.13') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119074410_1.0.0.13', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260120034948_AddedTableFields') THEN
    ALTER TABLE "ClientUsers" ADD "KycLevelCompleted" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260120034948_AddedTableFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260120034948_AddedTableFields', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "PayChannelAccounts" DROP CONSTRAINT "FK_PayChannelAccounts_AbpUsers_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "PayChannelCustomers" DROP CONSTRAINT "FK_PayChannelCustomers_AbpUsers_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "AbpUsers" DROP COLUMN "KycLevelCompleted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "PayChannelCustomers" ALTER COLUMN "UserId" TYPE integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "PayChannelAccounts" ALTER COLUMN "UserId" TYPE integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    CREATE TABLE "PayChannelServiceRequests" (
        "Id" uuid NOT NULL,
        "UserId" integer NOT NULL,
        "Currency" character varying(10) NOT NULL,
        "ChannelProvider" character varying(32) NOT NULL,
        "RequestPayload" text,
        "Status" integer NOT NULL,
        "FailStep" integer NOT NULL,
        "FailReason" text,
        "CustomerId" character varying(64),
        "AccountId" character varying(64),
        "CustomerResponse" text,
        "AccountResponse" text,
        "RetryCount" integer NOT NULL,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_PayChannelServiceRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayChannelServiceRequests_ClientUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ClientUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    CREATE INDEX "IX_PayChannelServiceRequests_UserId" ON "PayChannelServiceRequests" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "PayChannelAccounts" ADD CONSTRAINT "FK_PayChannelAccounts_ClientUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ClientUsers" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    ALTER TABLE "PayChannelCustomers" ADD CONSTRAINT "FK_PayChannelCustomers_ClientUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ClientUsers" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121085827_Add_PayChannelServiceRequests_Table') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260121085827_Add_PayChannelServiceRequests_Table', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121103600_Add_Unique_Index_For_Requests') THEN
    DROP INDEX "IX_PayChannelServiceRequests_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121103600_Add_Unique_Index_For_Requests') THEN
    CREATE UNIQUE INDEX "IX_PayChannelServiceRequests_UserId_ChannelProvider_Currency" ON "PayChannelServiceRequests" ("UserId", "ChannelProvider", "Currency") WHERE "Status" NOT IN (4, 5);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121103600_Add_Unique_Index_For_Requests') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260121103600_Add_Unique_Index_For_Requests', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    ALTER TABLE "Alliances" ADD "CopyrightInfo" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    ALTER TABLE "Alliances" ADD "Disclaimer" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    ALTER TABLE "Alliances" ADD "ServiceEmail" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    ALTER TABLE "Alliances" ADD "ThemeColor" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    ALTER TABLE "Alliances" ADD "WebSiteIcon" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    ALTER TABLE "Alliances" ADD "WebSiteUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123035123_1.0.0.14') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260123035123_1.0.0.14', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123072356_Add_PayChannelTransactions_Table') THEN
    CREATE TABLE "PayChannelTransactions" (
        "Id" uuid NOT NULL,
        "ChannelAccountId" uuid NOT NULL,
        "ChannelProvider" character varying(32) NOT NULL,
        "OrderNo" character varying(64) NOT NULL,
        "OutOrderNo" character varying(64),
        "OutUserId" character varying(64),
        "Amount" numeric(18,4) NOT NULL,
        "Currency" character varying(10) NOT NULL,
        "Reference" character varying(256),
        "PaymentType" character varying(32),
        "Status" character varying(32),
        "BizType" character varying(32),
        "BizStatus" character varying(32),
        "SettlementStatus" character varying(32),
        "SettlementAmount" numeric(18,4),
        "SettlementCurrency" character varying(10),
        "SettlementFee" numeric(18,4),
        "SettlementFeeCurrency" character varying(10),
        "SettlementTime" timestamp with time zone,
        "SenderName" character varying(256),
        "SenderAccountNumber" character varying(64),
        "SenderIban" character varying(64),
        "SenderSwiftBic" character varying(32),
        "RecipientAccountId" character varying(64),
        "RecipientCurrency" character varying(10),
        "RecipientIban" character varying(64),
        "RecipientSwiftBic" character varying(32),
        "RecipientBankCountry" character varying(10),
        "RecipientBankAddress" character varying(256),
        "RecipientAccountNumber" character varying(64),
        "RecipientBankName" character varying(256),
        "RecipientBankAccountHolderName" character varying(256),
        "TransactionCreationTime" timestamp with time zone,
        "TransactionCompletionTime" timestamp with time zone,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_PayChannelTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayChannelTransactions_PayChannelAccounts_ChannelAccountId" FOREIGN KEY ("ChannelAccountId") REFERENCES "PayChannelAccounts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123072356_Add_PayChannelTransactions_Table') THEN
    CREATE INDEX "IX_PayChannelTransactions_ChannelAccountId" ON "PayChannelTransactions" ("ChannelAccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260123072356_Add_PayChannelTransactions_Table') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260123072356_Add_PayChannelTransactions_Table', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127080145_AddMiddleNameToKycApplicant') THEN
    ALTER TABLE "AppKycApplicants" ADD "FixedMiddleName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127080145_AddMiddleNameToKycApplicant') THEN
    ALTER TABLE "AppKycApplicants" ADD "FixedMiddleNameEn" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127080145_AddMiddleNameToKycApplicant') THEN
    ALTER TABLE "AppKycApplicants" ADD "MiddleName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127080145_AddMiddleNameToKycApplicant') THEN
    ALTER TABLE "AppKycApplicants" ADD "MiddleNameEn" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127080145_AddMiddleNameToKycApplicant') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260127080145_AddMiddleNameToKycApplicant', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128100859_1.0.0.15') THEN
    ALTER TABLE "AbpUsers" ADD "TimeZoneValue" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128100859_1.0.0.15') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260128100859_1.0.0.15', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304040834_AddProductNameToAlliance') THEN
    ALTER TABLE "Alliances" ADD "ProductName" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304040834_AddProductNameToAlliance') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260304040834_AddProductNameToAlliance', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304082930_order') THEN
    CREATE TABLE "CollectionOrderDetails" (
        "Id" uuid NOT NULL,
        "CollectionOrderId" uuid NOT NULL,
        "PayerName" character varying(50),
        "PayerCurrency" character varying(10),
        "PayerIban" character varying(50),
        "PayerSwiftBic" character varying(50),
        "RecipientName" character varying(50),
        "RecipientCurrency" character varying(10),
        "RecipientAccountHolderName" character varying(50),
        "RecipientAccountNumber" character varying(50),
        "RecipientIban" character varying(50),
        "RecipientSwiftBic" character varying(50),
        "RecipientBankName" character varying(50),
        "RecipientBankAddress" character varying(256),
        "RecipientBankCountry" character varying(50),
        "SortCode" text,
        "RequestInfo" json,
        "ResponseInfo" json,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_CollectionOrderDetails" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304082930_order') THEN
    CREATE TABLE "CollectionOrders" (
        "Id" uuid NOT NULL,
        "PlatformOrderNo" character varying(50),
        "ChannelOrderNo" character varying(50),
        "AllianceId" integer NOT NULL,
        "AllianceName" character varying(50),
        "MerchantId" integer NOT NULL,
        "MerchantName" character varying(50),
        "UserId" integer NOT NULL,
        "UserName" character varying(50),
        "UserEmail" text,
        "Amount" numeric NOT NULL,
        "Currency" character varying(10),
        "ChannelCode" character varying(50),
        "PaymentMethod" character varying(50),
        "OrderType" integer NOT NULL,
        "OrderStatus" integer NOT NULL,
        "PayerName" character varying(50),
        "RecipientName" character varying(50),
        "AccountId" uuid NOT NULL,
        "Reference" character varying(256),
        "Remark" character varying(256),
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_CollectionOrders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260304082930_order') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260304082930_order', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305025102_paySettings') THEN
    ALTER TABLE "Merchants" ADD "PaySettings" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305025102_paySettings') THEN
    CREATE TABLE "MerchantPaySettings" (
        "Id" uuid NOT NULL,
        "MerchantId" integer NOT NULL,
        "MerchantName" text,
        "Type" integer NOT NULL,
        "Currency" character varying(10),
        "PaymentMethod" character varying(10),
        "ChannelCode" character varying(10),
        "Status" integer NOT NULL,
        "Operator" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_MerchantPaySettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305025102_paySettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260305025102_paySettings', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305035811_removepaySettings') THEN
    DROP TABLE "MerchantPaySettings";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305035811_removepaySettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260305035811_removepaySettings', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305035941_addpaySettingsV2') THEN
    CREATE TABLE "MerchantPaySettings" (
        "Id" uuid NOT NULL,
        "MerchantId" integer NOT NULL,
        "MerchantName" text,
        "Type" integer NOT NULL,
        "Currency" character varying(10),
        "PaymentMethod" character varying(50),
        "ChannelCode" character varying(50),
        "Status" integer NOT NULL,
        "Operator" text,
        "CreationTime" timestamp with time zone NOT NULL,
        "CreatorUserId" bigint,
        "LastModificationTime" timestamp with time zone,
        "LastModifierUserId" bigint,
        "IsDeleted" boolean NOT NULL,
        "DeleterUserId" bigint,
        "DeletionTime" timestamp with time zone,
        CONSTRAINT "PK_MerchantPaySettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260305035941_addpaySettingsV2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260305035941_addpaySettingsV2', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306020900_AddUserTypeToCollectionOrder') THEN
    ALTER TABLE "CollectionOrders" ADD "UserType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306020900_AddUserTypeToCollectionOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260306020900_AddUserTypeToCollectionOrder', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306024659_AddCallbackToCollectionOrder') THEN
    ALTER TABLE "CollectionOrders" ADD "Callback" character varying(512);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306024659_AddCallbackToCollectionOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260306024659_AddCallbackToCollectionOrder', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306025053_AddCallbackToCollectionOrder2') THEN
    ALTER TABLE "CollectionOrders" DROP COLUMN "Callback";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306025053_AddCallbackToCollectionOrder2') THEN
    ALTER TABLE "CollectionOrderDetails" ADD "Callback" character varying(512);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306025053_AddCallbackToCollectionOrder2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260306025053_AddCallbackToCollectionOrder2', '9.0.5');
    END IF;
END $EF$;
COMMIT;

