using System.Collections.Generic;

namespace ClientPlatform.BasicDataManagement
{
    public static class CountryConstants
    {
        public class CountryDef
        {
            public string Name { get; set; }
            public string CNName { get; set; }
            public string CCA2 { get; set; }
            public string CCA3 { get; set; }
        }

        public static readonly List<CountryDef> Countries = new List<CountryDef>
        {
            new CountryDef { Name = "Andorra", CNName = "安道尔", CCA2 = "AD", CCA3 = "AND" },
            new CountryDef { Name = "United Arab Emirates", CNName = "阿联酋", CCA2 = "AE", CCA3 = "ARE" },
            new CountryDef { Name = "Afghanistan", CNName = "阿富汗", CCA2 = "AF", CCA3 = "AFG" },
            new CountryDef { Name = "Antigua and Barbuda", CNName = "安提瓜和巴布达", CCA2 = "AG", CCA3 = "ATG" },
            new CountryDef { Name = "Anguilla", CNName = "安圭拉", CCA2 = "AI", CCA3 = "AIA" },
            new CountryDef { Name = "Albania", CNName = "阿尔巴尼亚", CCA2 = "AL", CCA3 = "ALB" },
            new CountryDef { Name = "Armenia", CNName = "亚美尼亚", CCA2 = "AM", CCA3 = "ARM" },
            new CountryDef { Name = "Angola", CNName = "安哥拉", CCA2 = "AO", CCA3 = "AGO" },
            new CountryDef { Name = "Antarctica", CNName = "南极洲", CCA2 = "AQ", CCA3 = "ATA" },
            new CountryDef { Name = "Argentina", CNName = "阿根廷", CCA2 = "AR", CCA3 = "ARG" },
            new CountryDef { Name = "American Samoa", CNName = "美属萨摩亚", CCA2 = "AS", CCA3 = "ASM" },
            new CountryDef { Name = "Austria", CNName = "奥地利", CCA2 = "AT", CCA3 = "AUT" },
            new CountryDef { Name = "Australia", CNName = "澳大利亚", CCA2 = "AU", CCA3 = "AUS" },
            new CountryDef { Name = "Aruba", CNName = "阿鲁巴", CCA2 = "AW", CCA3 = "ABW" },
            new CountryDef { Name = "Åland Islands", CNName = "奥兰群岛", CCA2 = "AX", CCA3 = "ALA" },
            new CountryDef { Name = "Azerbaijan", CNName = "阿塞拜疆", CCA2 = "AZ", CCA3 = "AZE" },
            new CountryDef { Name = "Bosnia and Herzegovina", CNName = "波斯尼亚和黑塞哥维那", CCA2 = "BA", CCA3 = "BIH" },
            new CountryDef { Name = "Barbados", CNName = "巴巴多斯", CCA2 = "BB", CCA3 = "BRB" },
            new CountryDef { Name = "Bangladesh", CNName = "孟加拉国", CCA2 = "BD", CCA3 = "BGD" },
            new CountryDef { Name = "Belgium", CNName = "比利时", CCA2 = "BE", CCA3 = "BEL" },
            new CountryDef { Name = "Burkina Faso", CNName = "布基纳法索", CCA2 = "BF", CCA3 = "BFA" },
            new CountryDef { Name = "Bulgaria", CNName = "保加利亚", CCA2 = "BG", CCA3 = "BGR" },
            new CountryDef { Name = "Bahrain", CNName = "巴林", CCA2 = "BH", CCA3 = "BHR" },
            new CountryDef { Name = "Burundi", CNName = "布隆迪", CCA2 = "BI", CCA3 = "BDI" },
            new CountryDef { Name = "Benin", CNName = "贝宁", CCA2 = "BJ", CCA3 = "BEN" },
            new CountryDef { Name = "Saint Barthélemy", CNName = "圣巴泰勒米", CCA2 = "BL", CCA3 = "BLM" },
            new CountryDef { Name = "Bermuda", CNName = "百慕大", CCA2 = "BM", CCA3 = "BMU" },
            new CountryDef { Name = "Brunei Darussalam", CNName = "文莱", CCA2 = "BN", CCA3 = "BRN" },
            new CountryDef { Name = "Bolivia", CNName = "玻利维亚", CCA2 = "BO", CCA3 = "BOL" },
            new CountryDef { Name = "Bonaire, Sint Eustatius and Saba", CNName = "博内尔、圣尤斯特歇斯和萨巴", CCA2 = "BQ", CCA3 = "BES" },
            new CountryDef { Name = "Brazil", CNName = "巴西", CCA2 = "BR", CCA3 = "BRA" },
            new CountryDef { Name = "Bahamas", CNName = "巴哈马", CCA2 = "BS", CCA3 = "BHS" },
            new CountryDef { Name = "Bhutan", CNName = "不丹", CCA2 = "BT", CCA3 = "BTN" },
            new CountryDef { Name = "Bouvet Island", CNName = "布韦岛", CCA2 = "BV", CCA3 = "BVT" },
            new CountryDef { Name = "Botswana", CNName = "博茨瓦纳", CCA2 = "BW", CCA3 = "BWA" },
            new CountryDef { Name = "Belarus", CNName = "白俄罗斯", CCA2 = "BY", CCA3 = "BLR" },
            new CountryDef { Name = "Belize", CNName = "伯利兹", CCA2 = "BZ", CCA3 = "BLZ" },
            new CountryDef { Name = "Canada", CNName = "加拿大", CCA2 = "CA", CCA3 = "CAN" },
            new CountryDef { Name = "Cocos (Keeling) Islands", CNName = "科科斯（基林）群岛", CCA2 = "CC", CCA3 = "CCK" },
            new CountryDef { Name = "Congo, Democratic Republic of the", CNName = "刚果（金）", CCA2 = "CD", CCA3 = "COD" },
            new CountryDef { Name = "Central African Republic", CNName = "中非共和国", CCA2 = "CF", CCA3 = "CAF" },
            new CountryDef { Name = "Congo", CNName = "刚果（布）", CCA2 = "CG", CCA3 = "COG" },
            new CountryDef { Name = "Switzerland", CNName = "瑞士", CCA2 = "CH", CCA3 = "CHE" },
            new CountryDef { Name = "Côte d'Ivoire", CNName = "科特迪瓦", CCA2 = "CI", CCA3 = "CIV" },
            new CountryDef { Name = "Cook Islands", CNName = "库克群岛", CCA2 = "CK", CCA3 = "COK" },
            new CountryDef { Name = "Chile", CNName = "智利", CCA2 = "CL", CCA3 = "CHL" },
            new CountryDef { Name = "Cameroon", CNName = "喀麦隆", CCA2 = "CM", CCA3 = "CMR" },
            new CountryDef { Name = "China", CNName = "中国", CCA2 = "CN", CCA3 = "CHN" },
            new CountryDef { Name = "Colombia", CNName = "哥伦比亚", CCA2 = "CO", CCA3 = "COL" },
            new CountryDef { Name = "Costa Rica", CNName = "哥斯达黎加", CCA2 = "CR", CCA3 = "CRI" },
            new CountryDef { Name = "Cuba", CNName = "古巴", CCA2 = "CU", CCA3 = "CUB" },
            new CountryDef { Name = "Cabo Verde", CNName = "佛得角", CCA2 = "CV", CCA3 = "CPV" },
            new CountryDef { Name = "Curaçao", CNName = "库拉索", CCA2 = "CW", CCA3 = "CUW" },
            new CountryDef { Name = "Christmas Island", CNName = "圣诞岛", CCA2 = "CX", CCA3 = "CXR" },
            new CountryDef { Name = "Cyprus", CNName = "塞浦路斯", CCA2 = "CY", CCA3 = "CYP" },
            new CountryDef { Name = "Czechia", CNName = "捷克", CCA2 = "CZ", CCA3 = "CZE" },
            new CountryDef { Name = "Germany", CNName = "德国", CCA2 = "DE", CCA3 = "DEU" },
            new CountryDef { Name = "Djibouti", CNName = "吉布提", CCA2 = "DJ", CCA3 = "DJI" },
            new CountryDef { Name = "Denmark", CNName = "丹麦", CCA2 = "DK", CCA3 = "DNK" },
            new CountryDef { Name = "Dominica", CNName = "多米尼克", CCA2 = "DM", CCA3 = "DMA" },
            new CountryDef { Name = "Dominican Republic", CNName = "多米尼加共和国", CCA2 = "DO", CCA3 = "DOM" },
            new CountryDef { Name = "Algeria", CNName = "阿尔及利亚", CCA2 = "DZ", CCA3 = "DZA" },
            new CountryDef { Name = "Ecuador", CNName = "厄瓜多尔", CCA2 = "EC", CCA3 = "ECU" },
            new CountryDef { Name = "Estonia", CNName = "爱沙尼亚", CCA2 = "EE", CCA3 = "EST" },
            new CountryDef { Name = "Egypt", CNName = "埃及", CCA2 = "EG", CCA3 = "EGY" },
            new CountryDef { Name = "Western Sahara", CNName = "西撒哈拉", CCA2 = "EH", CCA3 = "ESH" },
            new CountryDef { Name = "Eritrea", CNName = "厄立特里亚", CCA2 = "ER", CCA3 = "ERI" },
            new CountryDef { Name = "Spain", CNName = "西班牙", CCA2 = "ES", CCA3 = "ESP" },
            new CountryDef { Name = "Ethiopia", CNName = "埃塞俄比亚", CCA2 = "ET", CCA3 = "ETH" },
            new CountryDef { Name = "Finland", CNName = "芬兰", CCA2 = "FI", CCA3 = "FIN" },
            new CountryDef { Name = "Fiji", CNName = "斐济", CCA2 = "FJ", CCA3 = "FJI" },
            new CountryDef { Name = "Falkland Islands", CNName = "福克兰群岛", CCA2 = "FK", CCA3 = "FLK" },
            new CountryDef { Name = "Micronesia", CNName = "密克罗尼西亚", CCA2 = "FM", CCA3 = "FSM" },
            new CountryDef { Name = "Faroe Islands", CNName = "法罗群岛", CCA2 = "FO", CCA3 = "FRO" },
            new CountryDef { Name = "France", CNName = "法国", CCA2 = "FR", CCA3 = "FRA" },
            new CountryDef { Name = "Gabon", CNName = "加蓬", CCA2 = "GA", CCA3 = "GAB" },
            new CountryDef { Name = "United Kingdom", CNName = "英国", CCA2 = "GB", CCA3 = "GBR" },
            new CountryDef { Name = "Grenada", CNName = "格林纳达", CCA2 = "GD", CCA3 = "GRD" },
            new CountryDef { Name = "Georgia", CNName = "格鲁吉亚", CCA2 = "GE", CCA3 = "GEO" },
            new CountryDef { Name = "French Guiana", CNName = "法属圭亚那", CCA2 = "GF", CCA3 = "GUF" },
            new CountryDef { Name = "Guernsey", CNName = "根西岛", CCA2 = "GG", CCA3 = "GGY" },
            new CountryDef { Name = "Ghana", CNName = "加纳", CCA2 = "GH", CCA3 = "GHA" },
            new CountryDef { Name = "Gibraltar", CNName = "直布罗陀", CCA2 = "GI", CCA3 = "GIB" },
            new CountryDef { Name = "Greenland", CNName = "格陵兰", CCA2 = "GL", CCA3 = "GRL" },
            new CountryDef { Name = "Gambia", CNName = "冈比亚", CCA2 = "GM", CCA3 = "GMB" },
            new CountryDef { Name = "Guinea", CNName = "几内亚", CCA2 = "GN", CCA3 = "GIN" },
            new CountryDef { Name = "Guadeloupe", CNName = "瓜德罗普", CCA2 = "GP", CCA3 = "GLP" },
            new CountryDef { Name = "Equatorial Guinea", CNName = "赤道几内亚", CCA2 = "GQ", CCA3 = "GNQ" },
            new CountryDef { Name = "Greece", CNName = "希腊", CCA2 = "GR", CCA3 = "GRC" },
            new CountryDef { Name = "South Georgia and the South Sandwich Islands", CNName = "南乔治亚和南桑威奇群岛", CCA2 = "GS", CCA3 = "SGS" },
            new CountryDef { Name = "Guatemala", CNName = "危地马拉", CCA2 = "GT", CCA3 = "GTM" },
            new CountryDef { Name = "Guam", CNName = "关岛", CCA2 = "GU", CCA3 = "GUM" },
            new CountryDef { Name = "Guinea-Bissau", CNName = "几内亚比绍", CCA2 = "GW", CCA3 = "GNB" },
            new CountryDef { Name = "Guyana", CNName = "圭亚那", CCA2 = "GY", CCA3 = "GUY" },
            new CountryDef { Name = "Hong Kong", CNName = "香港", CCA2 = "HK", CCA3 = "HKG" },
            new CountryDef { Name = "Heard Island and McDonald Islands", CNName = "赫德岛和麦克唐纳群岛", CCA2 = "HM", CCA3 = "HMD" },
            new CountryDef { Name = "Honduras", CNName = "洪都拉斯", CCA2 = "HN", CCA3 = "HND" },
            new CountryDef { Name = "Croatia", CNName = "克罗地亚", CCA2 = "HR", CCA3 = "HRV" },
            new CountryDef { Name = "Haiti", CNName = "海地", CCA2 = "HT", CCA3 = "HTI" },
            new CountryDef { Name = "Hungary", CNName = "匈牙利", CCA2 = "HU", CCA3 = "HUN" },
            new CountryDef { Name = "Indonesia", CNName = "印度尼西亚", CCA2 = "ID", CCA3 = "IDN" },
            new CountryDef { Name = "Ireland", CNName = "爱尔兰", CCA2 = "IE", CCA3 = "IRL" },
            new CountryDef { Name = "Israel", CNName = "以色列", CCA2 = "IL", CCA3 = "ISR" },
            new CountryDef { Name = "Isle of Man", CNName = "马恩岛", CCA2 = "IM", CCA3 = "IMN" },
            new CountryDef { Name = "India", CNName = "印度", CCA2 = "IN", CCA3 = "IND" },
            new CountryDef { Name = "British Indian Ocean Territory", CNName = "英属印度洋领地", CCA2 = "IO", CCA3 = "IOT" },
            new CountryDef { Name = "Iraq", CNName = "伊拉克", CCA2 = "IQ", CCA3 = "IRQ" },
            new CountryDef { Name = "Iran", CNName = "伊朗", CCA2 = "IR", CCA3 = "IRN" },
            new CountryDef { Name = "Iceland", CNName = "冰岛", CCA2 = "IS", CCA3 = "ISL" },
            new CountryDef { Name = "Italy", CNName = "意大利", CCA2 = "IT", CCA3 = "ITA" },
            new CountryDef { Name = "Jersey", CNName = "泽西岛", CCA2 = "JE", CCA3 = "JEY" },
            new CountryDef { Name = "Jamaica", CNName = "牙买加", CCA2 = "JM", CCA3 = "JAM" },
            new CountryDef { Name = "Jordan", CNName = "约旦", CCA2 = "JO", CCA3 = "JOR" },
            new CountryDef { Name = "Japan", CNName = "日本", CCA2 = "JP", CCA3 = "JPN" },
            new CountryDef { Name = "Kenya", CNName = "肯尼亚", CCA2 = "KE", CCA3 = "KEN" },
            new CountryDef { Name = "Kyrgyzstan", CNName = "吉尔吉斯斯坦", CCA2 = "KG", CCA3 = "KGZ" },
            new CountryDef { Name = "Cambodia", CNName = "柬埔寨", CCA2 = "KH", CCA3 = "KHM" },
            new CountryDef { Name = "Kiribati", CNName = "基里巴斯", CCA2 = "KI", CCA3 = "KIR" },
            new CountryDef { Name = "Comoros", CNName = "科摩罗", CCA2 = "KM", CCA3 = "COM" },
            new CountryDef { Name = "Saint Kitts and Nevis", CNName = "圣基茨和尼维斯", CCA2 = "KN", CCA3 = "KNA" },
            new CountryDef { Name = "North Korea", CNName = "朝鲜", CCA2 = "KP", CCA3 = "PRK" },
            new CountryDef { Name = "South Korea", CNName = "韩国", CCA2 = "KR", CCA3 = "KOR" },
            new CountryDef { Name = "Kuwait", CNName = "科威特", CCA2 = "KW", CCA3 = "KWT" },
            new CountryDef { Name = "Cayman Islands", CNName = "开曼群岛", CCA2 = "KY", CCA3 = "CYM" },
            new CountryDef { Name = "Kazakhstan", CNName = "哈萨克斯坦", CCA2 = "KZ", CCA3 = "KAZ" },
            new CountryDef { Name = "Lao People's Democratic Republic", CNName = "老挝", CCA2 = "LA", CCA3 = "LAO" },
            new CountryDef { Name = "Lebanon", CNName = "黎巴嫩", CCA2 = "LB", CCA3 = "LBN" },
            new CountryDef { Name = "Saint Lucia", CNName = "圣卢西亚", CCA2 = "LC", CCA3 = "LCA" },
            new CountryDef { Name = "Liechtenstein", CNName = "列支敦士登", CCA2 = "LI", CCA3 = "LIE" },
            new CountryDef { Name = "Sri Lanka", CNName = "斯里兰卡", CCA2 = "LK", CCA3 = "LKA" },
            new CountryDef { Name = "Liberia", CNName = "利比里亚", CCA2 = "LR", CCA3 = "LBR" },
            new CountryDef { Name = "Lesotho", CNName = "莱索托", CCA2 = "LS", CCA3 = "LSO" },
            new CountryDef { Name = "Lithuania", CNName = "立陶宛", CCA2 = "LT", CCA3 = "LTU" },
            new CountryDef { Name = "Luxembourg", CNName = "卢森堡", CCA2 = "LU", CCA3 = "LUX" },
            new CountryDef { Name = "Latvia", CNName = "拉脱维亚", CCA2 = "LV", CCA3 = "LVA" },
            new CountryDef { Name = "Libya", CNName = "利比亚", CCA2 = "LY", CCA3 = "LBY" },
            new CountryDef { Name = "Morocco", CNName = "摩洛哥", CCA2 = "MA", CCA3 = "MAR" },
            new CountryDef { Name = "Monaco", CNName = "摩纳哥", CCA2 = "MC", CCA3 = "MCO" },
            new CountryDef { Name = "Moldova", CNName = "摩尔多瓦", CCA2 = "MD", CCA3 = "MDA" },
            new CountryDef { Name = "Montenegro", CNName = "黑山", CCA2 = "ME", CCA3 = "MNE" },
            new CountryDef { Name = "Saint Martin (French part)", CNName = "圣马丁", CCA2 = "MF", CCA3 = "MAF" },
            new CountryDef { Name = "Madagascar", CNName = "马达加斯加", CCA2 = "MG", CCA3 = "MDG" },
            new CountryDef { Name = "Marshall Islands", CNName = "马绍尔群岛", CCA2 = "MH", CCA3 = "MHL" },
            new CountryDef { Name = "North Macedonia", CNName = "北马其顿", CCA2 = "MK", CCA3 = "MKD" },
            new CountryDef { Name = "Mali", CNName = "马里", CCA2 = "ML", CCA3 = "MLI" },
            new CountryDef { Name = "Myanmar", CNName = "缅甸", CCA2 = "MM", CCA3 = "MMR" },
            new CountryDef { Name = "Mongolia", CNName = "蒙古", CCA2 = "MN", CCA3 = "MNG" },
            new CountryDef { Name = "Macao", CNName = "澳门", CCA2 = "MO", CCA3 = "MAC" },
            new CountryDef { Name = "Northern Mariana Islands", CNName = "北马里亚纳群岛", CCA2 = "MP", CCA3 = "MNP" },
            new CountryDef { Name = "Martinique", CNName = "马提尼克", CCA2 = "MQ", CCA3 = "MTQ" },
            new CountryDef { Name = "Mauritania", CNName = "毛里塔尼亚", CCA2 = "MR", CCA3 = "MRT" },
            new CountryDef { Name = "Montserrat", CNName = "蒙特塞拉特", CCA2 = "MS", CCA3 = "MSR" },
            new CountryDef { Name = "Malta", CNName = "马耳他", CCA2 = "MT", CCA3 = "MLT" },
            new CountryDef { Name = "Mauritius", CNName = "毛里求斯", CCA2 = "MU", CCA3 = "MUS" },
            new CountryDef { Name = "Maldives", CNName = "马尔代夫", CCA2 = "MV", CCA3 = "MDV" },
            new CountryDef { Name = "Malawi", CNName = "马拉维", CCA2 = "MW", CCA3 = "MWI" },
            new CountryDef { Name = "Mexico", CNName = "墨西哥", CCA2 = "MX", CCA3 = "MEX" },
            new CountryDef { Name = "Malaysia", CNName = "马来西亚", CCA2 = "MY", CCA3 = "MYS" },
            new CountryDef { Name = "Mozambique", CNName = "莫桑比克", CCA2 = "MZ", CCA3 = "MOZ" },
            new CountryDef { Name = "Namibia", CNName = "纳米比亚", CCA2 = "NA", CCA3 = "NAM" },
            new CountryDef { Name = "New Caledonia", CNName = "新喀里多尼亚", CCA2 = "NC", CCA3 = "NCL" },
            new CountryDef { Name = "Niger", CNName = "尼日尔", CCA2 = "NE", CCA3 = "NER" },
            new CountryDef { Name = "Norfolk Island", CNName = "诺福克岛", CCA2 = "NF", CCA3 = "NFK" },
            new CountryDef { Name = "Nigeria", CNName = "尼日利亚", CCA2 = "NG", CCA3 = "NGA" },
            new CountryDef { Name = "Nicaragua", CNName = "尼加拉瓜", CCA2 = "NI", CCA3 = "NIC" },
            new CountryDef { Name = "Netherlands", CNName = "荷兰", CCA2 = "NL", CCA3 = "NLD" },
            new CountryDef { Name = "Norway", CNName = "挪威", CCA2 = "NO", CCA3 = "NOR" },
            new CountryDef { Name = "Nepal", CNName = "尼泊尔", CCA2 = "NP", CCA3 = "NPL" },
            new CountryDef { Name = "Nauru", CNName = "瑙鲁", CCA2 = "NR", CCA3 = "NRU" },
            new CountryDef { Name = "Niue", CNName = "纽埃", CCA2 = "NU", CCA3 = "NIU" },
            new CountryDef { Name = "New Zealand", CNName = "新西兰", CCA2 = "NZ", CCA3 = "NZL" },
            new CountryDef { Name = "Oman", CNName = "阿曼", CCA2 = "OM", CCA3 = "OMN" },
            new CountryDef { Name = "Panama", CNName = "巴拿马", CCA2 = "PA", CCA3 = "PAN" },
            new CountryDef { Name = "Peru", CNName = "秘鲁", CCA2 = "PE", CCA3 = "PER" },
            new CountryDef { Name = "French Polynesia", CNName = "法属波利尼西亚", CCA2 = "PF", CCA3 = "PYF" },
            new CountryDef { Name = "Papua New Guinea", CNName = "巴布亚新几内亚", CCA2 = "PG", CCA3 = "PNG" },
            new CountryDef { Name = "Philippines", CNName = "菲律宾", CCA2 = "PH", CCA3 = "PHL" },
            new CountryDef { Name = "Pakistan", CNName = "巴基斯坦", CCA2 = "PK", CCA3 = "PAK" },
            new CountryDef { Name = "Poland", CNName = "波兰", CCA2 = "PL", CCA3 = "POL" },
            new CountryDef { Name = "Saint Pierre and Miquelon", CNName = "圣皮埃尔和密克隆", CCA2 = "PM", CCA3 = "SPM" },
            new CountryDef { Name = "Pitcairn", CNName = "皮特凯恩", CCA2 = "PN", CCA3 = "PCN" },
            new CountryDef { Name = "Puerto Rico", CNName = "波多黎各", CCA2 = "PR", CCA3 = "PRI" },
            new CountryDef { Name = "Palestinian Territory", CNName = "巴勒斯坦", CCA2 = "PS", CCA3 = "PSE" },
            new CountryDef { Name = "Portugal", CNName = "葡萄牙", CCA2 = "PT", CCA3 = "PRT" },
            new CountryDef { Name = "Palau", CNName = "帕劳", CCA2 = "PW", CCA3 = "PLW" },
            new CountryDef { Name = "Paraguay", CNName = "巴拉圭", CCA2 = "PY", CCA3 = "PRY" },
            new CountryDef { Name = "Qatar", CNName = "卡塔尔", CCA2 = "QA", CCA3 = "QAT" },
            new CountryDef { Name = "Réunion", CNName = "留尼汪", CCA2 = "RE", CCA3 = "REU" },
            new CountryDef { Name = "Romania", CNName = "罗马尼亚", CCA2 = "RO", CCA3 = "ROU" },
            new CountryDef { Name = "Serbia", CNName = "塞尔维亚", CCA2 = "RS", CCA3 = "SRB" },
            new CountryDef { Name = "Russian Federation", CNName = "俄罗斯", CCA2 = "RU", CCA3 = "RUS" },
            new CountryDef { Name = "Rwanda", CNName = "卢旺达", CCA2 = "RW", CCA3 = "RWA" },
            new CountryDef { Name = "Saudi Arabia", CNName = "沙特阿拉伯", CCA2 = "SA", CCA3 = "SAU" },
            new CountryDef { Name = "Solomon Islands", CNName = "所罗门群岛", CCA2 = "SB", CCA3 = "SLB" },
            new CountryDef { Name = "Seychelles", CNName = "塞舌尔", CCA2 = "SC", CCA3 = "SYC" },
            new CountryDef { Name = "Sudan", CNName = "苏丹", CCA2 = "SD", CCA3 = "SDN" },
            new CountryDef { Name = "Sweden", CNName = "瑞典", CCA2 = "SE", CCA3 = "SWE" },
            new CountryDef { Name = "Singapore", CNName = "新加坡", CCA2 = "SG", CCA3 = "SGP" },
            new CountryDef { Name = "Saint Helena", CNName = "圣赫勒拿", CCA2 = "SH", CCA3 = "SHN" },
            new CountryDef { Name = "Slovenia", CNName = "斯洛文尼亚", CCA2 = "SI", CCA3 = "SVN" },
            new CountryDef { Name = "Svalbard and Jan Mayen", CNName = "斯瓦尔巴和扬马延", CCA2 = "SJ", CCA3 = "SJM" },
            new CountryDef { Name = "Slovakia", CNName = "斯洛伐克", CCA2 = "SK", CCA3 = "SVK" },
            new CountryDef { Name = "Sierra Leone", CNName = "塞拉利昂", CCA2 = "SL", CCA3 = "SLE" },
            new CountryDef { Name = "San Marino", CNName = "圣马力诺", CCA2 = "SM", CCA3 = "SMR" },
            new CountryDef { Name = "Senegal", CNName = "塞内加尔", CCA2 = "SN", CCA3 = "SEN" },
            new CountryDef { Name = "Somalia", CNName = "索马里", CCA2 = "SO", CCA3 = "SOM" },
            new CountryDef { Name = "Suriname", CNName = "苏里南", CCA2 = "SR", CCA3 = "SUR" },
            new CountryDef { Name = "South Sudan", CNName = "南苏丹", CCA2 = "SS", CCA3 = "SSD" },
            new CountryDef { Name = "Sao Tome and Principe", CNName = "圣多美和普林西比", CCA2 = "ST", CCA3 = "STP" },
            new CountryDef { Name = "El Salvador", CNName = "萨尔瓦多", CCA2 = "SV", CCA3 = "SLV" },
            new CountryDef { Name = "Sint Maarten (Dutch part)", CNName = "圣马丁（荷兰）", CCA2 = "SX", CCA3 = "SXM" },
            new CountryDef { Name = "Syrian Arab Republic", CNName = "叙利亚", CCA2 = "SY", CCA3 = "SYR" },
            new CountryDef { Name = "Eswatini", CNName = "斯威士兰", CCA2 = "SZ", CCA3 = "SWZ" },
            new CountryDef { Name = "Turks and Caicos Islands", CNName = "特克斯和凯科斯群岛", CCA2 = "TC", CCA3 = "TCA" },
            new CountryDef { Name = "Chad", CNName = "乍得", CCA2 = "TD", CCA3 = "TCD" },
            new CountryDef { Name = "French Southern Territories", CNName = "法属南部领土", CCA2 = "TF", CCA3 = "ATF" },
            new CountryDef { Name = "Togo", CNName = "多哥", CCA2 = "TG", CCA3 = "TGO" },
            new CountryDef { Name = "Thailand", CNName = "泰国", CCA2 = "TH", CCA3 = "THA" },
            new CountryDef { Name = "Tajikistan", CNName = "塔吉克斯坦", CCA2 = "TJ", CCA3 = "TJK" },
            new CountryDef { Name = "Tokelau", CNName = "托克劳", CCA2 = "TK", CCA3 = "TKL" },
            new CountryDef { Name = "Timor-Leste", CNName = "东帝汶", CCA2 = "TL", CCA3 = "TLS" },
            new CountryDef { Name = "Turkmenistan", CNName = "土库曼斯坦", CCA2 = "TM", CCA3 = "TKM" },
            new CountryDef { Name = "Tunisia", CNName = "突尼斯", CCA2 = "TN", CCA3 = "TUN" },
            new CountryDef { Name = "Tonga", CNName = "汤加", CCA2 = "TO", CCA3 = "TON" },
            new CountryDef { Name = "Turkey", CNName = "土耳其", CCA2 = "TR", CCA3 = "TUR" },
            new CountryDef { Name = "Trinidad and Tobago", CNName = "特立尼达和多巴哥", CCA2 = "TT", CCA3 = "TTO" },
            new CountryDef { Name = "Tuvalu", CNName = "图瓦卢", CCA2 = "TV", CCA3 = "TUV" },
            new CountryDef { Name = "Taiwan", CNName = "中国台湾", CCA2 = "TW", CCA3 = "TWN" },
            new CountryDef { Name = "Tanzania", CNName = "坦桑尼亚", CCA2 = "TZ", CCA3 = "TZA" },
            new CountryDef { Name = "Ukraine", CNName = "乌克兰", CCA2 = "UA", CCA3 = "UKR" },
            new CountryDef { Name = "Uganda", CNName = "乌干达", CCA2 = "UG", CCA3 = "UGA" },
            new CountryDef { Name = "United States Minor Outlying Islands", CNName = "美国本土外小岛屿", CCA2 = "UM", CCA3 = "UMI" },
            new CountryDef { Name = "United States", CNName = "美国", CCA2 = "US", CCA3 = "USA" },
            new CountryDef { Name = "Uruguay", CNName = "乌拉圭", CCA2 = "UY", CCA3 = "URY" },
            new CountryDef { Name = "Uzbekistan", CNName = "乌兹别克斯坦", CCA2 = "UZ", CCA3 = "UZB" },
            new CountryDef { Name = "Holy See", CNName = "梵蒂冈", CCA2 = "VA", CCA3 = "VAT" },
            new CountryDef { Name = "Saint Vincent and the Grenadines", CNName = "圣文森特和格林纳丁斯", CCA2 = "VC", CCA3 = "VCT" },
            new CountryDef { Name = "Venezuela", CNName = "委内瑞拉", CCA2 = "VE", CCA3 = "VEN" },
            new CountryDef { Name = "Virgin Islands, British", CNName = "英属维尔京群岛", CCA2 = "VG", CCA3 = "VGB" },
            new CountryDef { Name = "Virgin Islands, U.S.", CNName = "美属维尔京群岛", CCA2 = "VI", CCA3 = "VIR" },
            new CountryDef { Name = "Viet Nam", CNName = "越南", CCA2 = "VN", CCA3 = "VNM" },
            new CountryDef { Name = "Vanuatu", CNName = "瓦努阿图", CCA2 = "VU", CCA3 = "VUT" },
            new CountryDef { Name = "Wallis and Futuna", CNName = "瓦利斯和富图纳", CCA2 = "WF", CCA3 = "WLF" },
            new CountryDef { Name = "Samoa", CNName = "萨摩亚", CCA2 = "WS", CCA3 = "WSM" },
            new CountryDef { Name = "Yemen", CNName = "也门", CCA2 = "YE", CCA3 = "YEM" },
            new CountryDef { Name = "Mayotte", CNName = "马约特", CCA2 = "YT", CCA3 = "MYT" },
            new CountryDef { Name = "South Africa", CNName = "南非", CCA2 = "ZA", CCA3 = "ZAF" },
            new CountryDef { Name = "Zambia", CNName = "赞比亚", CCA2 = "ZM", CCA3 = "ZMB" },
            new CountryDef { Name = "Zimbabwe", CNName = "津巴布韦", CCA2 = "ZW", CCA3 = "ZWE" }
        };
    }
}
